version: '3.8'

services:
  backend:
    build: ./backend
    container_name: kotloff-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./react-app
    container_name: kotloff-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped