services:
  # Бэкенд (NestJS)
  - type: web
    name: kotloff-backend
    runtime: image
    repo: https://github.com/valerahthfthfh/WebSite
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: NODE_ENV
        value: production

  # Фронтенд (React)
  - type: web
    name: kotloff-frontend
    runtime: image
    repo: https://github.com/valerahthfthfh/WebSite
    dockerfilePath: ./react-app/Dockerfile
    dockerContext: ./react-app
    envVars:
      - key: REACT_APP_API_URL
        value: https://kotloff-backend.onrender.com


  - type: worker           # или web, если нужен Flask
    name: kotloff-telegram-bot
    runtime: python
    rootDir: telegram-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8033399130:AAGI_89YLNq-FBrD5CacJK0bBSqtC7hwSdc
      - key: MAIN_ADMIN_ID
        value: "804822685"