services:
  # Бэкенд (NestJS)
  - type: web
    name: kotloff-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production

  # Фронтенд (React)
  - type: web
    name: kotloff-frontend
    runtime: static
    rootDir: react-app
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://kotloff-backend.onrender.com